language: c++
compiler:
#  - clang
  - gcc

sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
cache:
  apt: true
  directories:
  - "$HOME/.travis/cmake/build/install"

before_install:
  - if [ "$CC"  == "gcc" ]; then export CC=gcc-6; fi
  - if [ "$CXX" == "g++" ]; then export CXX=g++-6; fi
  - pushd . && cd $HOME
  - git clone https://github.com/LB--/travis.git travis
  - source "./travis/update-cmake.sh"
  - popd

install:
  - if [ "$CXX" == "g++-6" ]; then pip install --user cpp-coveralls; fi

script:
  - pushd .
  - mkdir build && cd build
  - cmake .. "-DCMAKE_INSTALL_PREFIX=$(pwd)/install" "-DCMAKE_CXX_FLAGS=--coverage -fno-inline -fno-inline-small-functions -fno-default-inline"
  - cmake --build . --target install
  - ctest -VV
  - popd

after_success:
  - if [ "$CXX" == "g++-6" ]; then coveralls --include "$(pwd)/src/" --include "$(pwd)/example/" --gcov /usr/bin/gcov-6 --gcov-options '\-lp'; fi
